#ifndef SMART_HOME_USER_DAO_HPP
#define SMART_HOME_USER_DAO_HPP

#include "MySqlClient.hpp"

#include <cstdint>
#include <string>

namespace shms {

struct UserRecord {
    std::uint64_t id;
    std::string name;
    std::string setting;
    std::string encrypt;
};

// DAO for the t_user table defined by the database design document. Password
// hashing is deliberately outside this class; it receives only the generated
// setting and ciphertext and uses prepared statements for both writes/reads.
class UserDao {
public:
    explicit UserDao(MySqlClient& client);
    UserDao(const UserDao&) = delete;
    UserDao& operator=(const UserDao&) = delete;

    // Create the table if it does not exist. Production deployments may run
    // database/schema.sql separately, while tests can call this idempotently.
    bool initializeSchema();

    // Insert one user. setting/encrypt are already generated by the account
    // service; plaintext passwords must never be passed to this method.
    bool createUser(const std::string& name,
                    const std::string& setting,
                    const std::string& encrypt,
                    std::uint64_t* userId = nullptr);

    // Find a user without treating "not found" as a database failure.
    bool findByName(const std::string& name,
                    UserRecord* record,
                    bool* found);

    std::string lastError() const;

private:
    bool setError(const std::string& message);
    void clearError();

    MySqlClient& client_;
    std::string lastError_;
};

}  // namespace shms

#endif  // SMART_HOME_USER_DAO_HPP
